--- #YAML:1.0
name:               IO-Compress
version:            2.039
abstract:           IO Interface to compressed data files/buffers
author:
    - Paul Marquess <pmqs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Compress::Raw::Bzip2:  2.039
    Compress::Raw::Zlib:  2.039
    Scalar::Util:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
